### ISSUE TITLE
mDNS passthrough Dockerfile

### ISSUE THREAD

**Issue by GeertRoks** [GeertRoks/rpi_radioHAT_multiroom#3]
The Librespot service in the snapcast server creates a Spotify connect service that broadcasts over mDNS. However, this service is only available on the docker network, so a method needs to be found to passthrough this mDNS.

A simple way is to set the container to use `network_mode: host`, but if it is possible to avoid this, that would be preferable.

**Comment by GeertRoks** [comment]
There seem to be various solutions to this:

1) use `network_mode: host`. The mDNS service will be broadcast on local network, but there is no seperation between host and container.
2) passthrough the mDNS/Avahi from container to host. reference: https://medium.com/@andrejtaneski/using-mdns-from-a-docker-container-b516a408a66b. Have not got it working and you arelinking the avahi and dbus services of the host and container.
3) Use a macvlan to let the container have an ip address on the network while still being separate from the host. Reference: https://forums.docker.com/t/how-do-i-attach-a-macvlan-network-and-assign-a-static-ip-address-in-compose-file/107419.

I like the 3rd option the best by creating an external macvlan network, so that you don't have to store ip network and network interface specifics in the docker compose and just attach the external network.

**Comment by GeertRoks** [comment]
Even better:

Define the macvlan in the docker compose, so that the macvlan lives as long as the stack does and store the network information in an .env file

```
---
services:

  snapserver:
    ...
    env_file:
      - .env
    networks:
      snapcast_network:
        ipv4_address: ${SNAPSERVER_IP}
 
 ...

networks:
  snapcast_network:
    driver: macvlan
    driver_opts:
      parent: ${MACVLAN_PARENT_INTERFACE}
    ipam:
      config:
        - subnet: ${MACVLAN_SUBNET}
          ip_range: ${MACVLAN_IP}
          gateway: ${MACVLAN_GATEWAY}
```

.env file
```
MACVLAN_PARENT_INTERFACE=
MACVLAN_SUBNET=
MACVLAN_IP=
MACVLAN_GATEWAY=
SNAPSERVER_IP=
```
